name: deploy to server

on: 
 push:
   branches: ["main"]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: "14" 
      - name: install dependancy
        run: npm install
      - name: build project
        run: npm run build

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: copy files via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /var/www/html
            git clone https://srinuboya02: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@github.com/srinuboya02/srinuproject22
            cd srinuproject22
            git pull
            npm install
            npm run build
